version: '3.0'

services:
  app:
    build: apps/backend
    image: registry.gitlab.com/abab5/bit-rx/backend:${TAG:-main}
    container_name: "losses-backend"
    networks:
      - internal
    env_file:
      - configs/docker/losses.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bitrx
      - POSTGRES_HOST=db
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: postgres:14.0
    container_name: "losses-db"
    command: postgres -c max_connections=400 -c shared_buffers=800MB
    networks:
      - internal
    ports:
      - "5432:5432"
    env_file:
      - configs/docker/losses.env
    volumes:
      - ./var/data/postgres/data:/var/lib/postgresql/data
      - ./configs/initdb.d:/docker-entrypoint-initdb.d/
    restart: on-failure:3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  frontend:
    build: apps/frontend
    image: registry.gitlab.com/abab5/bit-rx/frontend:${TAG:-main}
    container_name: "losses-frontend"
    ports:
      - 3000:3000
    stdin_open: true

networks:
  internal:
    driver: bridge
